FROM ubuntu:24.04

ENV PYTHONUNBUFFERED=1

ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && \
    apt-get install -y --no-install-recommends sudo tzdata locales curl ca-certificates git build-essential libcurl4-openssl-dev xvfb libva-dev libdrm-dev && \
    rm -rf /var/lib/apt/lists/*

RUN sed -i -e 's/# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen && locale-gen
ENV LANG=en_US.UTF-8
ENV LANGUAGE=en_US:en
ENV LC_ALL=en_US.UTF-8

ENV NVIDIA_VISIBLE_DEVICES=all
ENV NVIDIA_DRIVER_CAPABILITIES=graphics,utility,compute

ARG USER=batman
ARG USER_UID=1001
RUN useradd -m -s /bin/bash -u $USER_UID $USER
RUN usermod -aG sudo $USER
RUN echo '%sudo ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers
USER $USER

ENV OPENPILOT_PATH=/home/$USER/openpilot
RUN mkdir -p ${OPENPILOT_PATH}
WORKDIR ${OPENPILOT_PATH}

COPY --chown=$USER . ${OPENPILOT_PATH}/

ARG UV_HTTP_TIMEOUT=300
ARG UV_REQUEST_TIMEOUT=300
ARG UV_SYNC_ARGS="--frozen"
ENV UV_BIN="/home/$USER/.local/bin/"
ENV VIRTUAL_ENV=${OPENPILOT_PATH}/.venv
ENV DOCKER_CACHE_PATH=${OPENPILOT_PATH}/.docker-cache
ENV UV_HTTP_TIMEOUT=${UV_HTTP_TIMEOUT}
ENV UV_REQUEST_TIMEOUT=${UV_REQUEST_TIMEOUT}
ENV UV_SYNC_ARGS=${UV_SYNC_ARGS}
ENV SKIP_SYSTEM_DEPS=1
ENV UV_CONCURRENT_DOWNLOADS=1
ENV UV_CONCURRENT_BUILDS=1
ENV UV_FIND_LINKS=${DOCKER_CACHE_PATH}/wheels
ENV PATH="$UV_BIN:$VIRTUAL_ENV/bin:$PATH"
RUN test -d "${DOCKER_CACHE_PATH}/dependencies.git"
RUN test -f "${DOCKER_CACHE_PATH}/wheels/gcc_arm_none_eabi-13.2.1-py3-none-linux_x86_64.whl"
RUN git config --global url."file://${DOCKER_CACHE_PATH}/dependencies.git".insteadOf "https://github.com/commaai/dependencies.git"
RUN tools/setup_dependencies.sh && \
    sudo rm -rf /var/lib/apt/lists/*
RUN chmod a+rx /home/$USER /home/$USER/openpilot && \
    chmod -R a+rX ${VIRTUAL_ENV}

USER root
RUN git config --global --add safe.directory '*'
